blank_issues_enabled: false
contact_links:
  - name: Questions and general discussions around rust_ci_experiments
    url: https://github.com/AlexAegis/rust_ci_experiments/discussions
    about: For general discussions, or questions please use discussions.
